// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvLDm9b_AJnbSdQL7SEvWSwRHWUwkarZ0',
    appId: '1:1092835414521:web:176d0c67d5b3eb27a5ad28',
    messagingSenderId: '1092835414521',
    projectId: 'tictaktoe-multiplayer-flutter',
    authDomain: 'tictaktoe-multiplayer-flutter.firebaseapp.com',
    storageBucket: 'tictaktoe-multiplayer-flutter.firebasestorage.app',
    measurementId: 'G-3CH15M4FDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO2GW7XKLur10_EzA7rEctjdZG_neXX0A',
    appId: '1:1092835414521:android:87efc5485da814f8a5ad28',
    messagingSenderId: '1092835414521',
    projectId: 'tictaktoe-multiplayer-flutter',
    storageBucket: 'tictaktoe-multiplayer-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDryz9tSY0FD2ejrzL4s6WPGS7RYP0E2SY',
    appId: '1:1092835414521:ios:2caa67192ec695c7a5ad28',
    messagingSenderId: '1092835414521',
    projectId: 'tictaktoe-multiplayer-flutter',
    storageBucket: 'tictaktoe-multiplayer-flutter.firebasestorage.app',
    iosBundleId: 'com.example.tictaktoeMultiplayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDryz9tSY0FD2ejrzL4s6WPGS7RYP0E2SY',
    appId: '1:1092835414521:ios:2caa67192ec695c7a5ad28',
    messagingSenderId: '1092835414521',
    projectId: 'tictaktoe-multiplayer-flutter',
    storageBucket: 'tictaktoe-multiplayer-flutter.firebasestorage.app',
    iosBundleId: 'com.example.tictaktoeMultiplayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvLDm9b_AJnbSdQL7SEvWSwRHWUwkarZ0',
    appId: '1:1092835414521:web:ebc15bdd77b045d3a5ad28',
    messagingSenderId: '1092835414521',
    projectId: 'tictaktoe-multiplayer-flutter',
    authDomain: 'tictaktoe-multiplayer-flutter.firebaseapp.com',
    storageBucket: 'tictaktoe-multiplayer-flutter.firebasestorage.app',
    measurementId: 'G-WYG7PWW6P5',
  );
}
