// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAimeoOpVBcxPcswhD42tkhVY2o9rc5AH4',
    appId: '1:319135341284:web:9a557e4e99aa702a7b2af1',
    messagingSenderId: '319135341284',
    projectId: 'tictaktoe-game-f0f5c',
    authDomain: 'tictaktoe-game-f0f5c.firebaseapp.com',
    storageBucket: 'tictaktoe-game-f0f5c.firebasestorage.app',
    measurementId: 'G-BPWTH5H0RY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBIa-8q9Pp_tqlMzoRg0RNC9s3-PAAiWc',
    appId: '1:319135341284:android:6da70de910c5ede77b2af1',
    messagingSenderId: '319135341284',
    projectId: 'tictaktoe-game-f0f5c',
    storageBucket: 'tictaktoe-game-f0f5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiAGewNzQJDHg5oG9L6-r8rB60ttEDql8',
    appId: '1:319135341284:ios:a07d18ed029fa5d37b2af1',
    messagingSenderId: '319135341284',
    projectId: 'tictaktoe-game-f0f5c',
    storageBucket: 'tictaktoe-game-f0f5c.firebasestorage.app',
    iosBundleId: 'com.example.tictaktoeGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiAGewNzQJDHg5oG9L6-r8rB60ttEDql8',
    appId: '1:319135341284:ios:a07d18ed029fa5d37b2af1',
    messagingSenderId: '319135341284',
    projectId: 'tictaktoe-game-f0f5c',
    storageBucket: 'tictaktoe-game-f0f5c.firebasestorage.app',
    iosBundleId: 'com.example.tictaktoeGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAimeoOpVBcxPcswhD42tkhVY2o9rc5AH4',
    appId: '1:319135341284:web:55a19bbcb03c3e177b2af1',
    messagingSenderId: '319135341284',
    projectId: 'tictaktoe-game-f0f5c',
    authDomain: 'tictaktoe-game-f0f5c.firebaseapp.com',
    storageBucket: 'tictaktoe-game-f0f5c.firebasestorage.app',
    measurementId: 'G-DQN0FCC6L2',
  );
}
